# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rehline_ <- function(Xmat, Amat, bvec, Umat, Vmat, Smat, Tmat, TauMat, max_iter, tol, shrink = TRUE, verbose = 0L, trace_freq = 100L) {
    .Call(`_rehline_rehline_impl`, Xmat, Amat, bvec, Umat, Vmat, Smat, Tmat, TauMat, max_iter, tol, shrink, verbose, trace_freq)
}

